
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 600)
        Dialog.setMinimumSize(QtCore.QSize(500, 600))
        Dialog.setMaximumSize(QtCore.QSize(650, 600))
        Dialog.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_frame = QtWidgets.QFrame(Dialog)
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.header_left_frame = QtWidgets.QFrame(self.header_frame)
        self.header_left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_left_frame.setObjectName("header_left_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.header_left_frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tekno_logo_left = QtWidgets.QLabel(self.header_left_frame)
        self.tekno_logo_left.setMaximumSize(QtCore.QSize(80, 65))
        self.tekno_logo_left.setText("")
        self.tekno_logo_left.setPixmap(QtGui.QPixmap(":/feather/feather_beyaz/AKSXAkzWtSKS1EnC4zlsSRPqEqjXe4Gl.png"))
        self.tekno_logo_left.setScaledContents(True)
        self.tekno_logo_left.setObjectName("tekno_logo_left")
        self.horizontalLayout_6.addWidget(self.tekno_logo_left)
        self.horizontalLayout.addWidget(self.header_left_frame)
        self.header_top_frame = QtWidgets.QFrame(self.header_frame)
        self.header_top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_top_frame.setObjectName("header_top_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.header_top_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.huma_arge_label = QtWidgets.QLabel(self.header_top_frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.huma_arge_label.setFont(font)
        self.huma_arge_label.setStyleSheet("font: 75 36pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.huma_arge_label.setObjectName("huma_arge_label")
        self.horizontalLayout_3.addWidget(self.huma_arge_label)
        self.horizontalLayout.addWidget(self.header_top_frame)
        self.header_right_frame = QtWidgets.QFrame(self.header_frame)
        self.header_right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_right_frame.setObjectName("header_right_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.header_right_frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tekno__logo_rght = QtWidgets.QLabel(self.header_right_frame)
        self.tekno__logo_rght.setMaximumSize(QtCore.QSize(80, 65))
        self.tekno__logo_rght.setText("")
        self.tekno__logo_rght.setPixmap(QtGui.QPixmap(":/feather/feather_beyaz/AKSXAkzWtSKS1EnC4zlsSRPqEqjXe4Gl.png"))
        self.tekno__logo_rght.setScaledContents(True)
        self.tekno__logo_rght.setObjectName("tekno__logo_rght")
        self.horizontalLayout_5.addWidget(self.tekno__logo_rght)
        self.horizontalLayout.addWidget(self.header_right_frame)
        self.verticalLayout.addWidget(self.header_frame)
        self.lock_frame = QtWidgets.QFrame(Dialog)
        self.lock_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lock_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lock_frame.setObjectName("lock_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.lock_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lock = QtWidgets.QLabel(self.lock_frame)
        self.lock.setMinimumSize(QtCore.QSize(50, 0))
        self.lock.setMaximumSize(QtCore.QSize(180, 210))
        self.lock.setText("")
        self.lock.setPixmap(QtGui.QPixmap(":/feather/feather_beyaz/locked.png"))
        self.lock.setScaledContents(True)
        self.lock.setObjectName("lock")
        self.horizontalLayout_4.addWidget(self.lock)
        self.verticalLayout.addWidget(self.lock_frame)
        self.login_frame = QtWidgets.QFrame(Dialog)
        self.login_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_frame.setObjectName("login_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.login_frame)
        self.verticalLayout_2.setContentsMargins(60, 20, 60, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.password_lineedit = QtWidgets.QLineEdit(self.login_frame)
        self.password_lineedit.setMinimumSize(QtCore.QSize(30, 35))
        self.password_lineedit.setInputMask("")
        self.password_lineedit.setText("")
        self.password_lineedit.setObjectName("password_lineedit")
        self.verticalLayout_2.addWidget(self.password_lineedit)
        self.hata_mesaj = QtWidgets.QLabel(self.login_frame)
        self.hata_mesaj.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 75 9pt \"MS Shell Dlg 2\";")
        self.hata_mesaj.setObjectName("hata_mesaj")
        self.verticalLayout_2.addWidget(self.hata_mesaj)
        self.giris_btn = QtWidgets.QPushButton(self.login_frame)
        self.giris_btn.setMinimumSize(QtCore.QSize(182, 55))
        self.giris_btn.setMaximumSize(QtCore.QSize(180, 70))
        self.giris_btn.setStyleSheet("QPushButton#giris_btn{\n"
"\n"
"    background-color:rgb(254, 194, 0);\n"
"    border-style: outset;\n"
"    border-width: 3px;\n"
"    border-radius: 27px;\n"
"    border-color: beige;\n"
"    font: bold 20px;\n"
"    min-width: 7em;\n"
"    padding: 4px;\n"
"\n"
"}\n"
"\n"
"QPushButton#giris_btn:hover{\n"
"    background-color: rgb(170, 54, 54) ;\n"
"    border-style: inset;\n"
"}\n"
"\n"
"")
        self.giris_btn.setIconSize(QtCore.QSize(180, 180))
        self.giris_btn.setObjectName("giris_btn")
        self.verticalLayout_2.addWidget(self.giris_btn, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.login_frame)
        self.footer_frame = QtWidgets.QFrame(Dialog)
        self.footer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer_frame.setObjectName("footer_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.footer_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left_footer_framer = QtWidgets.QFrame(self.footer_frame)
        self.left_footer_framer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_footer_framer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_footer_framer.setObjectName("left_footer_framer")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.left_footer_framer)
        self.horizontalLayout_7.setContentsMargins(0, 20, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.huma_logo = QtWidgets.QLabel(self.left_footer_framer)
        self.huma_logo.setMinimumSize(QtCore.QSize(50, 0))
        self.huma_logo.setMaximumSize(QtCore.QSize(250, 80))
        self.huma_logo.setText("")
        self.huma_logo.setPixmap(QtGui.QPixmap(":/feather/feather_beyaz/logo_siyah.png"))
        self.huma_logo.setScaledContents(True)
        self.huma_logo.setObjectName("huma_logo")
        self.horizontalLayout_7.addWidget(self.huma_logo, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_2.addWidget(self.left_footer_framer)
        self.right_footer_frame = QtWidgets.QFrame(self.footer_frame)
        self.right_footer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_footer_frame.setObjectName("right_footer_frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.right_footer_frame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 10, 10)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.insta_btn = QtWidgets.QPushButton(self.right_footer_frame)
        self.insta_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/feather/feather_beyaz/3955024.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.insta_btn.setIcon(icon)
        self.insta_btn.setIconSize(QtCore.QSize(32, 32))
        self.insta_btn.setObjectName("insta_btn")
        self.horizontalLayout_8.addWidget(self.insta_btn, 0, QtCore.Qt.AlignLeft)
        self.gkleren_agv_footer = QtWidgets.QLabel(self.right_footer_frame)
        self.gkleren_agv_footer.setStyleSheet("color : rgb(244, 163, 0);\n"
"font: 75 15pt \"MS Shell Dlg 2\";\n"
"")
        self.gkleren_agv_footer.setScaledContents(False)
        self.gkleren_agv_footer.setObjectName("gkleren_agv_footer")
        self.horizontalLayout_8.addWidget(self.gkleren_agv_footer, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.horizontalLayout_2.addWidget(self.right_footer_frame, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.footer_frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.huma_arge_label.setText(_translate("Dialog", "HUMA AR-GE "))
        self.password_lineedit.setPlaceholderText(_translate("Dialog", "PASSWORD GİRİNİZ"))
        self.hata_mesaj.setText(_translate("Dialog", "."))
        self.giris_btn.setText(_translate("Dialog", "LOGİN"))
        self.gkleren_agv_footer.setText(_translate("Dialog", "GÖKLEREN AGV"))
import icons_rc
